
# Jessica Barón Martínez Código: 200924758 
# Silverio Carmona Código: 200924758 



## Exercise 05

# Neural networks

## 4.1 Little Red Riding Hood Network

Train a neural network to solve the  Little Red Riding Hood problem in sklern and Keras. Try the neural networ with different inputs and report the results.

________________

## 4.2 Boston House Price Prediction

In the next questions we are going to work using the dataset *Boston*. This dataset measures the influence of socioeconomical factors on the price of several estates of the city of Boston. This dataset has 506 instances, each one characterized by 13 features:

* CRIM - per capita crime rate by town
* ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
* INDUS - proportion of non-retail business acres per town.
* CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
* NOX - nitric oxides concentration (parts per 10 million)
* RM - average number of rooms per dwelling
* AGE - proportion of owner-occupied units built prior to 1940
* DIS - weighted distances to five Boston employment centres
* RAD - index of accessibility to radial highways
* TAX - full-value property-tax rate per 10,000 USD
* PTRATIO - pupil-teacher ratio by town
* B - $1000(Bk - 0.63)^2$ where $Bk$ is the proportion of blacks by town
* LSTAT - % lower status of the population

Output variable:
* MEDV - Median value of owner-occupied homes in 1000's USD

**Note:** In this exercise we are going to predict the price of each estate, which is represented in the `MEDV` variable. It is important to remember that we are always aiming to predict `MEDV`, no matter which explanatory variables we are using. That means, in some cases we will use a subset of the 13 previously mentioned variables, while in other cases we will use all the 13 variables. But in no case we will change the dependent variable $y$.



1. Load the dataset using `from sklearn.datasets import load_boston`.
2. Create a DataFrame using the attribute `.data` from the loading function of Scikit-learn.
3. Assign the columns of the DataFrame so they match the `.feature_names` attribute from the loading function of Scikit-learn. 
4. Assign a new column to the DataFrame which holds the value to predict, that means, the `.target` attribute of the loading function of Scikit-learn. The name of this columns must be `MEDV`.
5. Use the function `.describe()` from Pandas for obtaining statistics about each column.

## 4.3 Feature analysis:

Using the DataFrame generated in the previous section:
* Filter the dataset to just these features:
     * Explanatory: 'LSTAT', 'INDUS', 'NOX', 'RM', 'AGE'
     * Dependent: 'MEDV'.
* Generate a scatter matrix among the features mentioned above using Pandas (`scatter_matrix`) or Seaborn (` pairplot`).
     * Do you find any relationship between the features?
* Generate the correlation matrix between these variables using `numpy.corrcoef`. Also include `MEDV`.
     * Which characteristics are more correlated?
     * BONUS: Visualize this matrix as heat map using Pandas, Matplotlib or Seaborn.

## 4.4 Modeling linear and non linear relationships

* Generate two new subsets filtering these characteristics:
     * $D_1$:  $X = \textit{'RM'}$, $y = \textit{'MEDV'}$
     * $D_2$:  $X = \textit{'LSTAT'}$, $y = \textit{'MEDV'}$
* For each subset, generate a training partition and a test partition using a ratio of $ 70 \% - 30 \% $
* Train a linear regression model on both subsets of data:
     * Report the mean square error on the test set
     * Print the values of $ w $ and $ w_0 $ of the regression equation
     * Generate a graph where you visualize the line obtained by the regression model in conjunction with the training data and the test data
* How does the model perform on $ D_1 $ and $ D_2 $? Why?

## 4.5 Training a regression model

* Generate a 70-30 partitioning of the data **using all the features**. (Do not include the dependent variable `MEDV`)
* Train a linear regression model with the objective of predicting the output variable `MEDV`.
     * Report the mean square error on the test set
* Train a regression model using `MLPRegressor` in order to predict the output variable` MEDV`.
     * Report the mean square error on the test set
* Scale the data so that they have zero mean variance one per feature (only $ X $). You can use the following piece of code:

```python
from sklearn.preprocessing import StandardScaler

sc_x = StandardScaler()
sc_x.fit(X)
X_train_s = sc_x.transform(X_train)
X_test_s = sc_x.transform(X_test)
```
Check more information about `StandardScaler` [here](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html).

* Train the following models:
     1. Train a linear regression model using the scaled data.
         * Report the mean square error on the test set
     2. Train a regression model using a 2-layer MultiLayer Perceptron (128 neurons in the first and 512 in the second) and with the **scaled data**.
         * Report the mean square error on the test set
     3. Which model has better performance? Why?

## SOLUCIÓN

## 4.1 Little Red Riding Hood Network
Train a neural network to solve the Little Red Riding Hood problem in sklern and Keras. Try the neural networ with different inputs and report the results.

In [32]:
import numpy as np
import pylab as pl
from sklearn.datasets.samples_generator import make_moons
from keras.models import Sequential
from keras.layers.core import Dense


## 1. Neural network training in Keras
We will build a multilayer network to solve the following classification problem:

In [47]:
#Cargamos las 3 combinaciones par identiicar personaje

training_data=np.array([[1,1,0,0],[0,1,1,0],[0,0,0,1]], "float32") 

In [48]:
test_data  = np.array([[0,1,0,0],[1,0,0,0],[0,0,1,0]], "float32")

In [49]:
#Cargamos las 3 combinaciones que se obtienen par identificar personaje
target_data=np.array([[1,0,0,0],[0,0,1,1],[0,1,1,0]], "float32")

In [50]:
training_data

array([[1., 1., 0., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [51]:
target_data

array([[1., 0., 0., 0.],
       [0., 0., 1., 1.],
       [0., 1., 1., 0.]], dtype=float32)

## DEFINICIÓN DEL MODELO

In [52]:
model = Sequential()
model.add(Dense(20, input_dim=4, activation='relu'))
model.add(Dense(4, activation='sigmoid'))

In [53]:
model

## COPILACIÓN DEL MODELO

In [54]:
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

#elige automáticamente la mejor manera de representar la red para entrenar y hacer predicciones
#Se utiliza la pérdida logarítmica, que para un problema de clasificación binaria se define en Keras como “binary_crossentropy”.
#algoritmo de descenso de gradiente eficiente “adam” por su alta eficiencia.
#Debido a que es un problema de clasificación, recopilaremos y reportaremos la exactitud de la clasificación como la métrica "accuracy".

In [55]:
#Podemos comprobar nuestra arquitectura de modelo con el siguiente comando
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 20)                100       
_________________________________________________________________
dense_4 (Dense)              (None, 4)                 84        
Total params: 184
Trainable params: 184
Non-trainable params: 0
_________________________________________________________________


## ENTRENAMIENTO DEL MODELO

In [56]:
# Fit the model
model.fit(x=training_data,y=target_data, epochs=1000, batch_size=10)

#El proceso de entrenamiento se ejecutará para un número fijo de iteraciones denominado epochs o épocas.
#el número de instancias que se evalúan antes de que se realice una actualización de peso en la red llamada batch_size

Epoch 1/1000
3/3 [==============================] - 0s 73ms/step - loss: 0.7178 - acc: 0.5000
Epoch 2/1000
3/3 [==============================] - 0s 665us/step - loss: 0.7157 - acc: 0.5000
Epoch 3/1000
3/3 [==============================] - 0s 997us/step - loss: 0.7137 - acc: 0.5000
Epoch 4/1000
3/3 [==============================] - 0s 665us/step - loss: 0.7117 - acc: 0.5000
Epoch 5/1000
3/3 [==============================] - 0s 665us/step - loss: 0.7097 - acc: 0.5000
Epoch 6/1000
3/3 [==============================] - 0s 665us/step - loss: 0.7077 - acc: 0.5000
Epoch 7/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.7058 - acc: 0.5000
Epoch 8/1000
3/3 [==============================] - 0s 665us/step - loss: 0.7038 - acc: 0.5000
Epoch 9/1000
3/3 [==============================] - 0s 665us/step - loss: 0.7019 - acc: 0.5000
Epoch 10/1000
3/3 [==============================] - 0s 333us/step - loss: 0.6999 - acc: 0.5000
Epoch 11/1000
3/3 [==============================] -

Epoch 87/1000
3/3 [==============================] - 0s 665us/step - loss: 0.5521 - acc: 0.9167
Epoch 88/1000
3/3 [==============================] - 0s 665us/step - loss: 0.5502 - acc: 0.9167
Epoch 89/1000
3/3 [==============================] - 0s 665us/step - loss: 0.5482 - acc: 0.9167
Epoch 90/1000
3/3 [==============================] - 0s 665us/step - loss: 0.5463 - acc: 0.9167
Epoch 91/1000
3/3 [==============================] - 0s 665us/step - loss: 0.5444 - acc: 0.9167
Epoch 92/1000
3/3 [==============================] - 0s 332us/step - loss: 0.5425 - acc: 0.9167
Epoch 93/1000
3/3 [==============================] - 0s 332us/step - loss: 0.5405 - acc: 0.9167
Epoch 94/1000
3/3 [==============================] - 0s 997us/step - loss: 0.5386 - acc: 0.9167
Epoch 95/1000
3/3 [==============================] - 0s 665us/step - loss: 0.5367 - acc: 0.9167
Epoch 96/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.5347 - acc: 0.9167
Epoch 97/1000
3/3 [=======================

Epoch 172/1000
3/3 [==============================] - 0s 665us/step - loss: 0.3918 - acc: 1.0000
Epoch 173/1000
3/3 [==============================] - 0s 665us/step - loss: 0.3901 - acc: 1.0000
Epoch 174/1000
3/3 [==============================] - 0s 665us/step - loss: 0.3883 - acc: 1.0000
Epoch 175/1000
3/3 [==============================] - 0s 332us/step - loss: 0.3866 - acc: 1.0000
Epoch 176/1000
3/3 [==============================] - 0s 665us/step - loss: 0.3848 - acc: 1.0000
Epoch 177/1000
3/3 [==============================] - 0s 664us/step - loss: 0.3831 - acc: 1.0000
Epoch 178/1000
3/3 [==============================] - 0s 665us/step - loss: 0.3813 - acc: 1.0000
Epoch 179/1000
3/3 [==============================] - 0s 665us/step - loss: 0.3796 - acc: 1.0000
Epoch 180/1000
3/3 [==============================] - 0s 664us/step - loss: 0.3779 - acc: 1.0000
Epoch 181/1000
3/3 [==============================] - 0s 665us/step - loss: 0.3761 - acc: 1.0000
Epoch 182/1000
3/3 [==========

Epoch 257/1000
3/3 [==============================] - 0s 665us/step - loss: 0.2580 - acc: 1.0000
Epoch 258/1000
3/3 [==============================] - 0s 333us/step - loss: 0.2566 - acc: 1.0000
Epoch 259/1000
3/3 [==============================] - 0s 997us/step - loss: 0.2552 - acc: 1.0000
Epoch 260/1000
3/3 [==============================] - 0s 333us/step - loss: 0.2539 - acc: 1.0000
Epoch 261/1000
3/3 [==============================] - 0s 333us/step - loss: 0.2525 - acc: 1.0000
Epoch 262/1000
3/3 [==============================] - 0s 664us/step - loss: 0.2512 - acc: 1.0000
Epoch 263/1000
3/3 [==============================] - 0s 334us/step - loss: 0.2499 - acc: 1.0000
Epoch 264/1000
3/3 [==============================] - 0s 664us/step - loss: 0.2486 - acc: 1.0000
Epoch 265/1000
3/3 [==============================] - 0s 332us/step - loss: 0.2472 - acc: 1.0000
Epoch 266/1000
3/3 [==============================] - 0s 665us/step - loss: 0.2459 - acc: 1.0000
Epoch 267/1000
3/3 [==========

Epoch 342/1000
3/3 [==============================] - 0s 665us/step - loss: 0.1625 - acc: 1.0000
Epoch 343/1000
3/3 [==============================] - 0s 665us/step - loss: 0.1616 - acc: 1.0000
Epoch 344/1000
3/3 [==============================] - 0s 665us/step - loss: 0.1607 - acc: 1.0000
Epoch 345/1000
3/3 [==============================] - 0s 996us/step - loss: 0.1598 - acc: 1.0000
Epoch 346/1000
3/3 [==============================] - 0s 665us/step - loss: 0.1589 - acc: 1.0000
Epoch 347/1000
3/3 [==============================] - 0s 332us/step - loss: 0.1580 - acc: 1.0000
Epoch 348/1000
3/3 [==============================] - 0s 665us/step - loss: 0.1572 - acc: 1.0000
Epoch 349/1000
3/3 [==============================] - 0s 665us/step - loss: 0.1563 - acc: 1.0000
Epoch 350/1000
3/3 [==============================] - 0s 665us/step - loss: 0.1554 - acc: 1.0000
Epoch 351/1000
3/3 [==============================] - 0s 665us/step - loss: 0.1546 - acc: 1.0000
Epoch 352/1000
3/3 [==========

Epoch 427/1000
3/3 [==============================] - 0s 665us/step - loss: 0.1024 - acc: 1.0000
Epoch 428/1000
3/3 [==============================] - 0s 664us/step - loss: 0.1018 - acc: 1.0000
Epoch 429/1000
3/3 [==============================] - 0s 664us/step - loss: 0.1013 - acc: 1.0000
Epoch 430/1000
3/3 [==============================] - 0s 664us/step - loss: 0.1008 - acc: 1.0000
Epoch 431/1000
3/3 [==============================] - 0s 665us/step - loss: 0.1002 - acc: 1.0000
Epoch 432/1000
3/3 [==============================] - 0s 664us/step - loss: 0.0997 - acc: 1.0000
Epoch 433/1000
3/3 [==============================] - 0s 332us/step - loss: 0.0992 - acc: 1.0000
Epoch 434/1000
3/3 [==============================] - 0s 332us/step - loss: 0.0987 - acc: 1.0000
Epoch 435/1000
3/3 [==============================] - 0s 998us/step - loss: 0.0982 - acc: 1.0000
Epoch 436/1000
3/3 [==============================] - 0s 1ms/step - loss: 0.0976 - acc: 1.0000
Epoch 437/1000
3/3 [============

Epoch 512/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0666 - acc: 1.0000
Epoch 513/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0663 - acc: 1.0000
Epoch 514/1000
3/3 [==============================] - 0s 999us/step - loss: 0.0660 - acc: 1.0000
Epoch 515/1000
3/3 [==============================] - 0s 664us/step - loss: 0.0657 - acc: 1.0000
Epoch 516/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0654 - acc: 1.0000
Epoch 517/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0651 - acc: 1.0000
Epoch 518/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0647 - acc: 1.0000
Epoch 519/1000
3/3 [==============================] - 0s 333us/step - loss: 0.0644 - acc: 1.0000
Epoch 520/1000
3/3 [==============================] - 0s 332us/step - loss: 0.0641 - acc: 1.0000
Epoch 521/1000
3/3 [==============================] - 0s 332us/step - loss: 0.0638 - acc: 1.0000
Epoch 522/1000
3/3 [==========

Epoch 597/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0455 - acc: 1.0000
Epoch 598/1000
3/3 [==============================] - 0s 332us/step - loss: 0.0453 - acc: 1.0000
Epoch 599/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0451 - acc: 1.0000
Epoch 600/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0450 - acc: 1.0000
Epoch 601/1000
3/3 [==============================] - 0s 333us/step - loss: 0.0448 - acc: 1.0000
Epoch 602/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0446 - acc: 1.0000
Epoch 603/1000
3/3 [==============================] - 0s 333us/step - loss: 0.0444 - acc: 1.0000
Epoch 604/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0442 - acc: 1.0000
Epoch 605/1000
3/3 [==============================] - 0s 998us/step - loss: 0.0440 - acc: 1.0000
Epoch 606/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0439 - acc: 1.0000
Epoch 607/1000
3/3 [==========

Epoch 682/1000
3/3 [==============================] - 0s 664us/step - loss: 0.0326 - acc: 1.0000
Epoch 683/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0325 - acc: 1.0000
Epoch 684/1000
3/3 [==============================] - 0s 332us/step - loss: 0.0324 - acc: 1.0000
Epoch 685/1000
3/3 [==============================] - 0s 997us/step - loss: 0.0322 - acc: 1.0000
Epoch 686/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0321 - acc: 1.0000
Epoch 687/1000
3/3 [==============================] - 0s 332us/step - loss: 0.0320 - acc: 1.0000
Epoch 688/1000
3/3 [==============================] - 0s 332us/step - loss: 0.0319 - acc: 1.0000
Epoch 689/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0318 - acc: 1.0000
Epoch 690/1000
3/3 [==============================] - 0s 333us/step - loss: 0.0316 - acc: 1.0000
Epoch 691/1000
3/3 [==============================] - 0s 332us/step - loss: 0.0315 - acc: 1.0000
Epoch 692/1000
3/3 [==========

Epoch 767/1000
3/3 [==============================] - 0s 664us/step - loss: 0.0243 - acc: 1.0000
Epoch 768/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0242 - acc: 1.0000
Epoch 769/1000
3/3 [==============================] - 0s 333us/step - loss: 0.0241 - acc: 1.0000
Epoch 770/1000
3/3 [==============================] - 0s 333us/step - loss: 0.0240 - acc: 1.0000
Epoch 771/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0239 - acc: 1.0000
Epoch 772/1000
3/3 [==============================] - 0s 666us/step - loss: 0.0239 - acc: 1.0000
Epoch 773/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0238 - acc: 1.0000
Epoch 774/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0237 - acc: 1.0000
Epoch 775/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0236 - acc: 1.0000
Epoch 776/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0236 - acc: 1.0000
Epoch 777/1000
3/3 [==========

Epoch 852/1000
3/3 [==============================] - 0s 997us/step - loss: 0.0187 - acc: 1.0000
Epoch 853/1000
3/3 [==============================] - 0s 997us/step - loss: 0.0186 - acc: 1.0000
Epoch 854/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0186 - acc: 1.0000
Epoch 855/1000
3/3 [==============================] - 0s 333us/step - loss: 0.0185 - acc: 1.0000
Epoch 856/1000
3/3 [==============================] - 0s 664us/step - loss: 0.0184 - acc: 1.0000
Epoch 857/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0184 - acc: 1.0000
Epoch 858/1000
3/3 [==============================] - 0s 332us/step - loss: 0.0183 - acc: 1.0000
Epoch 859/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0183 - acc: 1.0000
Epoch 860/1000
3/3 [==============================] - 0s 332us/step - loss: 0.0182 - acc: 1.0000
Epoch 861/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0182 - acc: 1.0000
Epoch 862/1000
3/3 [==========

Epoch 937/1000
3/3 [==============================] - 0s 663us/step - loss: 0.0147 - acc: 1.0000
Epoch 938/1000
3/3 [==============================] - 0s 332us/step - loss: 0.0147 - acc: 1.0000
Epoch 939/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0147 - acc: 1.0000
Epoch 940/1000
3/3 [==============================] - 0s 663us/step - loss: 0.0146 - acc: 1.0000
Epoch 941/1000
3/3 [==============================] - 0s 332us/step - loss: 0.0146 - acc: 1.0000
Epoch 942/1000
3/3 [==============================] - 0s 333us/step - loss: 0.0145 - acc: 1.0000
Epoch 943/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0145 - acc: 1.0000
Epoch 944/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0145 - acc: 1.0000
Epoch 945/1000
3/3 [==============================] - 0s 664us/step - loss: 0.0144 - acc: 1.0000
Epoch 946/1000
3/3 [==============================] - 0s 665us/step - loss: 0.0144 - acc: 1.0000
Epoch 947/1000
3/3 [==========

## EVALUACIÓN DEL MODELO

In [57]:
scores = model.evaluate(training_data, target_data)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

3/3 [==============================] - 0s 18ms/step

acc: 100.00%


## PREDECIR

In [59]:
# calculate predictions
print (model.predict(test_data).round())


[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 1.]]


#El modelo predice que podemos tener
columns=['Big Ears', 'Big Teeth', 'Handsome', 'Wrinkled'])
1.no tiene grandes oidos ni grandes dientes, guapo y  no es viejo= CAPERUCITA ROJA
2.Tiene Grandes oidos= LOBO
3.No tiene grandes oidos ni grandes dientes, guapa y vieja o arrugado = ABUELITA